# Generated by Django 3.2.5 on 2021-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_subject_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='year',
            field=models.IntegerField(choices=[(0, 'Vsi letniki / drugo'), (1, '1. letnik'), (2, '2. letnik'), (3, '3. letnik'), (4, '4. letnik')], default=0),
        ),
    ]
