# Generated by Django 3.1.9 on 2021-08-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_submission_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
