# Generated by Django 3.2.6 on 2021-08-04 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_auto_20210802_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='username',
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='fas fa-graduation-cap', max_length=20),
        ),
    ]
